from ..core import Gene as Gene, Metabolite as Metabolite, Model as Model, Reaction as Reaction
from ..util.solver import set_objective as set_objective
from cobra import Object as Object
from collections import OrderedDict

def gene_from_dict(gene: dict) -> Gene: ...
def model_to_dict(model: Model, sort: bool = False) -> OrderedDict: ...
def model_from_dict(obj: dict) -> Model: ...
