from .dict import model_from_dict as model_from_dict, model_to_dict as model_to_dict
from cobra import Model as Model
from pathlib import Path
from typing import Any, IO

JSON_SPEC: str

def to_json(model: Model, sort: bool = False, **kwargs: Any) -> str: ...
def from_json(document: str) -> Model: ...
def save_json_model(model: Model, filename: str | Path | IO, sort: bool = False, pretty: bool = False, **kwargs: Any) -> None: ...
def load_json_model(filename: str | Path | IO) -> Model: ...
