#!/usr/bin/env bash
set -e

# Run `ruff check` only on staged files
files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.py$')
if [ -z "$files" ]; then
  exit 0
fi
ruff check --no-fix "$files"
status=$?
if [ $status -ne 0 ]; then
  echo "Ruff found issues. Commit aborted."
  exit 1
fi

# If `ruff check` is good, then format all staged files
ruff check --fix --select I "$files"
ruff format "$files"


exit 0
