zz <- file("/home/jupyteruser/work/py/rlogs/fitAgilent.Rout", open="wt")
sink(zz, type="message")

readaiglent <- function(addr,targets){
    crd <- getwd()
    setwd(addr)
    # targets <- dir(".", "txt.gz")
    x <- read.maimages(targets, "agilent", green.only = TRUE)
    setwd(crd)
    y <- backgroundCorrect(x,method="normexp") 
    y <- normalizeBetweenArrays(y,method="quantile") 
    yo <- c(y$genes,as.data.frame(y$E))
    ydf <- data.frame(yo)
    return(ydf)
}
fitagilent <- function(addr,target){
    crd <- getwd()
    setwd(addr)    
    targets <- readTargets(target)
    x <- read.maimages(targets, path="somedirectory", source="agilent",green.only=TRUE)
    y <- backgroundCorrect(x, method="normexp", offset=16)
    y <- normalizeBetweenArrays(y, method="quantile")
    y.ave <- avereps(y, ID=y$genes$ProbeName)
    f <- factor(targets$Condition, levels = unique(targets$Condition))
    design <- model.matrix(~0 + f)
    colnames(design) <- levels(f)
    fit <- lmFit(y.ave, design)
    contrast.matrix <- makeContrasts("Treatment1-Treatment2", "Treatment1-Treatment3", "Treatment2-Treatment1", levels=design)
    fit2 = contrasts.fit(fit,contrast.matrix)
    fit2 = eBayes(fit2)
    data = topTable(fit2,number = "inf")
    return(data)
    }