# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/opensource-nepal/commitlint
    rev: v1.2.0
    hooks:
    -   id: commitlint
        name: Commit Lint
