name: madrid
channels:
  - bioconda
  - conda-forge
  - r
  - default
dependencies:
  - bioconductor-affy
  - bioconductor-affyio
  - bioconductor-agilp
  - bioconductor-biomart
  - bioconductor-DESeq2
  - bioconductor-edger
  - bioconductor-genefilter
  - bioconductor-hgu133acdf
  - bioconductor-limma
  - bioservices
  - crux-toolkit
  - GEOparse
  - git
  - lxml
  - markupsafe==2.0.1
  - numpy
  - openpyxl
  - pandas
  - pip
  - r-biocmanager
  - r-devtools
  - r-ggrepel
  - r-irdisplay
  - r-irkernel
  - r-locfit
  - r-readxl
  - r-repr
  - r-rzmq
  - r-sjmisc
  - r-stringr
  - r-tidyverse
  - r-uwot
  - r-zoo
  - requests
  - rpy2
  - scipy
  - SQLAlchemy
  - thermorawfileparser
  - tqdm
  - unidecode
  - wget
  - xlrd
  - pip:
    - git+https://github.com/babessell1/cobamp.git@master#egg=cobamp
    - git+https://github.com/cokelaer/bioservices.git@master#egg=bioservices
    - cobra
    - escher
    - framed
    - gurobipy
    - memote
    - optlang
    - pytest==4.6.11
    - python-libsbml==5.19.4
    - troppo
