[project]
name = "COMO"
dynamic = ["version"]
requires-python = ">=3.10,<3.13"
dependencies = [
    "cobra>=0.28.0",
    "fast-bioservices>=0.3.9",
    "gurobipy>=11.0",
    "kaleido==0.2.1",
    "loguru>=0.7.2",
    "pandas>=1.3.5",
    "plotly>=5.24.1",
    "scanpy>=1.9.8",
    "scipy>=1.7.3",
    "scikit-learn>=1.5.2",
    "setuptools<60.0",
    "openpyxl>=3.1.5",
    "aiofiles>=24.1.0",
    "aioftp>=0.23.1",
    "troppo",
    "cobamp",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "main/como/__init__.py"

[tool.hatch.build]
packages = ["main/como"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.pytest.ini_options]
pythonpath = [ "main/src" ]

[tool.uv]
dev-dependencies = [
    "commitlint>=1.3.0",
    "pytest-asyncio>=0.24.0",
    "pytest>=8.3.3",
    "ruff>=0.8.0",
    "hypothesis>=6.122.1",
    "pytest-cov>=6.0.0",
]

#[tool.uv.sources]
#troppo = { git = "https://github.com/JoshLoecker/troppo", rev = "update_dependencies" }
#cobamp = { git = "https://github.com/JoshLoecker/cobamp", rev = "update_packages" }
