[project]
name = "COMO"
dynamic = ["version"]
requires-python = ">=3.10,<3.11"
dependencies = [
    #    "cobamp>=0.2.1",
    "cobra>=0.28.0",
    # latest is 0.29.1
    "fast-bioservices@git+https://github.com/JoshLoecker/fast_bioservices@drop-pandas-version",
    "gurobipy>=11.0",
    "kaleido==0.2.1",
    "loguru>=0.7.2",
    "numpy>=1.22.0,<1.23.0",
    # latest is 2.1.2
    "pandas>=1.3.5",
    # latest is 2.2.3
    "plotly>=5.24.1",
    "scanpy>=1.9.8",
    "scipy>=1.7.3",
    # latest is 1.14.1
    "scikit-learn>=1.5.2",
    "setuptools<60.0",
    "openpyxl>=3.1.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "main/como/__init__.py"

[tool.hatch.build]
packages = ["main/como"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
line-length = 150

[tool.ruff.lint]
ignore = ["F401"]

[tool.pytest.ini_options]
pythonpath = [ "main/src" ]

[tool.uv.sources]
troppo = { git = "https://github.com/JoshLoecker/troppo", rev = "update_dependencies" }
cobamp = { git = "https://github.com/JoshLoecker/cobamp", rev = "update_packages" }
