[general]
COMO_version = "1.8.0-master"

[rnaseq_preprocess]

[total_rnaseq_gen]

[mrna_rnaseq_gen]

[proteomics_gen]

[merge_xomics]

[cluster_rnaseq]

[create_context_specific_model]

[escher_map]

[disease_analysis]

[knock_out_simulation]
