from _typeshed import Incomplete

class OptimizationError(Exception):
    def __init__(self, message) -> None: ...

class Infeasible(OptimizationError): ...
class Unbounded(OptimizationError): ...
class FeasibleButNotOptimal(OptimizationError): ...
class UndefinedSolution(OptimizationError): ...
class SolverNotFound(Exception): ...

OPTLANG_TO_EXCEPTIONS_DICT: Incomplete
