from _typeshed import Incomplete
from ast import BoolOp, Name, NodeTransformer
from cobra import Gene as Gene, Metabolite as Metabolite, Model as Model, Reaction as Reaction
from cobra.util import get_context as get_context
from typing import Iterable

logger: Incomplete

def prune_unused_metabolites(model: Model) -> tuple['Model', list['Metabolite']]: ...
def prune_unused_reactions(model: Model) -> tuple['Model', list['Reaction']]: ...
def knock_out_model_genes(model: Model, gene_list: Iterable[Gene | int | str]) -> list['Reaction']: ...
def delete_model_genes(model: Model, gene_list: list['Gene'] | set['Gene'] | list[str] | set[str], cumulative_deletions: bool = True, disable_orphans: bool = False) -> None: ...

class _GeneRemover(NodeTransformer):
    target_genes: Incomplete
    def __init__(self, target_genes: set['Gene'], **kwargs) -> None: ...
    def visit_Name(self, node: Name) -> Name | None: ...
    def visit_BoolOp(self, node: BoolOp) -> BoolOp | Name | None: ...

def remove_genes(model: Model, gene_list: list['Gene'] | set['Gene'] | list[str] | str, remove_reactions: bool = True) -> None: ...
