from cobra import Metabolite as Metabolite, Model as Model, Reaction as Reaction

def check_mass_balance(model: Model) -> dict['Reaction', dict['Metabolite', float]]: ...
def check_metabolite_compartment_formula(model: Model) -> list[str]: ...
