from .object import Object as Object
from typing import Any, Callable, Iterable, Iterator, Pattern

class DictList(list):
    def __init__(self, *args) -> None: ...
    def has_id(self, id: Object | str) -> bool: ...
    def get_by_id(self, id: Object | str) -> Object: ...
    def list_attr(self, attribute: str) -> list: ...
    def get_by_any(self, iterable: list[str | Object | int]) -> list: ...
    def query(self, search_function: str | Pattern | Callable, attribute: str | None = None) -> DictList: ...
    def append(self, entity: Object) -> None: ...
    def union(self, iterable: Iterable[Object]) -> None: ...
    def extend(self, iterable: Iterable[Object]) -> None: ...
    def __sub__(self, other: Iterable[Object]) -> DictList: ...
    def __isub__(self, other: Iterable[Object]) -> DictList: ...
    def __add__(self, other: Iterable[Object]) -> DictList: ...
    def __iadd__(self, other: Iterable[Object]) -> DictList: ...
    def __reduce__(self) -> tuple[type['DictList'], tuple, dict, Iterator]: ...
    def index(self, id: str | Object, *args) -> int: ...
    def __contains__(self, entity: str | Object) -> bool: ...
    def __copy__(self) -> DictList: ...
    def insert(self, index: int, entity: Object) -> None: ...
    def pop(self, *args) -> Object: ...
    def add(self, x: Object) -> None: ...
    def remove(self, x: str | Object) -> None: ...
    def reverse(self) -> None: ...
    def sort(self, cmp: Callable = None, key: Callable = None, reverse: bool = False) -> None: ...
    def __getitem__(self, i: int | slice | Iterable | Object | DictList) -> DictList | Object: ...
    def __setitem__(self, i: slice | int, y: list | Object) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def __getslice__(self, i: int, j: int) -> DictList: ...
    def __setslice__(self, i: int, j: int, y: list | Object) -> None: ...
    def __delslice__(self, i: int, j: int) -> None: ...
    def __getattr__(self, attr: Any) -> Any: ...
    def __dir__(self) -> list: ...
