import sympy.logic.boolalg as spl
from ..util import resettable as resettable
from ..util.util import format_long_string as format_long_string
from .dictlist import DictList as DictList
from .species import Species as Species
from _typeshed import Incomplete
from ast import AST, BoolOp, Expression, Module, Name, NodeTransformer, NodeVisitor
from sympy import Symbol
from typing import Iterable

logger: Incomplete
keywords: Incomplete
keyword_re: Incomplete
number_start_re: Incomplete
replacements: Incomplete

class GPRWalker(NodeVisitor):
    gene_set: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def visit_Name(self, node: Name) -> None: ...
    def visit_BoolOp(self, node: BoolOp) -> None: ...

class GPRCleaner(NodeTransformer):
    gene_set: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def visit_Name(self, node: Name) -> Name: ...
    def visit_BinOp(self, node: BoolOp) -> None: ...

def parse_gpr(str_expr: str) -> tuple: ...

class Gene(Species):
    def __init__(self, id: str = None, name: str = '', functional: bool = True) -> None: ...
    @property
    def functional(self) -> bool: ...
    @functional.setter
    @resettable
    def functional(self, value: bool) -> None: ...
    def knock_out(self) -> None: ...

class GPR(Module):
    body: list | None
    def __init__(self, gpr_from: Expression | Module | AST = None, **kwargs) -> None: ...
    @classmethod
    def from_string(cls, string_gpr: str) -> GPR: ...
    @property
    def genes(self) -> frozenset: ...
    def update_genes(self) -> None: ...
    def eval(self, knockouts: DictList | set | str | Iterable = None) -> bool: ...
    def to_string(self, names: dict = None) -> str: ...
    def copy(self) -> GPR: ...
    def __copy__(self) -> GPR: ...
    def as_symbolic(self, names: dict = None) -> spl.Or | spl.And | Symbol: ...
    @classmethod
    def from_symbolic(cls, sympy_gpr: spl.BooleanFunction | Symbol) -> GPR: ...
    def __eq__(self, other) -> bool: ...

def eval_gpr(expr: Expression | GPR, knockouts: DictList | set) -> bool: ...
def ast2str(expr: Expression | GPR, level: int = 0, names: dict = None) -> str: ...
