from .object import Object as Object
from _typeshed import Incomplete
from typing import Iterable

class Group(Object):
    KIND_TYPES: Incomplete
    def __init__(self, id: str, name: str = '', members: Iterable | None = None, kind: str | None = None) -> None: ...
    def __len__(self) -> int: ...
    @property
    def members(self) -> set: ...
    @property
    def kind(self) -> str: ...
    @kind.setter
    def kind(self, kind: str) -> None: ...
    def add_members(self, new_members: list) -> None: ...
    def remove_members(self, to_remove: list) -> None: ...
