import optlang
import pandas as pd
import types
from ..medium import find_boundary_types as find_boundary_types, find_external_compartment as find_external_compartment, sbo_terms as sbo_terms
from ..util.context import HistoryManager as HistoryManager, get_context as get_context, resettable as resettable
from ..util.solver import add_cons_vars_to_problem as add_cons_vars_to_problem, assert_optimal as assert_optimal, check_solver as check_solver, interface_to_str as interface_to_str, remove_cons_vars_from_problem as remove_cons_vars_from_problem, set_objective as set_objective
from ..util.util import AutoVivification as AutoVivification, format_long_string as format_long_string
from .configuration import Configuration as Configuration
from .dictlist import DictList as DictList
from .gene import Gene as Gene
from .group import Group as Group
from .metabolite import Metabolite as Metabolite
from .object import Object as Object
from .reaction import Reaction as Reaction
from .solution import get_solution as get_solution
from _typeshed import Incomplete
from cobra import Solution as Solution
from cobra.summary import ModelSummary as ModelSummary
from cobra.util.solver import CONS_VARS as CONS_VARS
from optlang.container import Container as Container
from optlang.symbolics import Basic
from types import ModuleType
from typing import Iterable

logger: Incomplete
configuration: Incomplete

class Model(Object):
    genes: Incomplete
    reactions: Incomplete
    metabolites: Incomplete
    groups: Incomplete
    def __init__(self, id_or_model: str | Model | None = None, name: str | None = None) -> None: ...
    @property
    def solver(self) -> optlang.interface.Model: ...
    @solver.setter
    @resettable
    def solver(self, value: str | ModuleType) -> None: ...
    @property
    def tolerance(self) -> float: ...
    @tolerance.setter
    def tolerance(self, value: float) -> None: ...
    @property
    def compartments(self) -> dict: ...
    @compartments.setter
    def compartments(self, value: dict) -> None: ...
    @property
    def medium(self) -> dict[str, float]: ...
    @medium.setter
    def medium(self, medium: dict[str, float]) -> None: ...
    def copy(self) -> Model: ...
    def add_metabolites(self, metabolite_list: list | Metabolite) -> None: ...
    def remove_metabolites(self, metabolite_list: list | Metabolite, destructive: bool = False) -> None: ...
    def add_boundary(self, metabolite: Metabolite, type: str = 'exchange', reaction_id: str | None = None, lb: float | None = None, ub: float | None = None, sbo_term: str | None = None) -> Reaction: ...
    def add_reactions(self, reaction_list: Iterable[Reaction]) -> None: ...
    def remove_reactions(self, reactions: str | Reaction | list[str | Reaction], remove_orphans: bool = False) -> None: ...
    def add_groups(self, group_list: str | Group | list[Group]) -> None: ...
    def remove_groups(self, group_list: str | Group | list[Group]) -> None: ...
    def get_associated_groups(self, element: Reaction | Gene | Metabolite) -> list[Group]: ...
    def add_cons_vars(self, what: list['CONS_VARS'] | tuple['CONS_VARS'], **kwargs) -> None: ...
    def remove_cons_vars(self, what: list['CONS_VARS'] | tuple['CONS_VARS']) -> None: ...
    @property
    def problem(self) -> optlang.interface: ...
    @property
    def variables(self) -> Container: ...
    @property
    def constraints(self) -> Container: ...
    @property
    def boundary(self) -> list[Reaction]: ...
    @property
    def exchanges(self) -> list[Reaction]: ...
    @property
    def demands(self) -> list[Reaction]: ...
    @property
    def sinks(self) -> list[Reaction]: ...
    def slim_optimize(self, error_value: float | None = ..., message: str | None = None) -> float: ...
    def optimize(self, objective_sense: str | None = None, raise_error: bool = False) -> Solution: ...
    def repair(self, rebuild_index: bool = True, rebuild_relationships: bool = True) -> None: ...
    @property
    def objective(self) -> optlang.Objective: ...
    @objective.setter
    def objective(self, value: dict[Reaction, 'Container'] | str | int | Reaction | optlang.interface.Objective | Basic) -> None: ...
    @property
    def objective_direction(self) -> str: ...
    @objective_direction.setter
    @resettable
    def objective_direction(self, value: str) -> None: ...
    def summary(self, solution: Solution | None = None, fva: pd.DataFrame | float | None = None) -> ModelSummary: ...
    def __enter__(self) -> Model: ...
    def __exit__(self, type: type[BaseException] | None, value: BaseException | None, traceback: types.TracebackType | None) -> None: ...
    def merge(self, right: Model, prefix_existing: str | None = None, inplace: bool = True, objective: str = 'left') -> Model: ...
