from _typeshed import Incomplete

class Object:
    name: Incomplete
    notes: Incomplete
    def __init__(self, id: str | None = None, name: str = '') -> None: ...
    @property
    def id(self) -> str: ...
    @id.setter
    def id(self, value) -> None: ...
    @property
    def annotation(self) -> dict: ...
    @annotation.setter
    def annotation(self, annotation) -> None: ...
