import pandas as pd
from ..exceptions import OptimizationError as OptimizationError
from ..manipulation import remove_genes as remove_genes
from ..util.context import get_context as get_context, resettable as resettable
from ..util.solver import check_solver_status as check_solver_status, linear_reaction_coefficients as linear_reaction_coefficients, set_objective as set_objective
from ..util.util import format_long_string as format_long_string
from .configuration import Configuration as Configuration
from .gene import GPR as GPR, Gene as Gene
from .metabolite import Metabolite as Metabolite
from .object import Object as Object
from _typeshed import Incomplete
from cobra import Model as Model, Solution as Solution
from cobra.summary import ReactionSummary as ReactionSummary
from optlang.interface import Variable as Variable
from typing import AnyStr, Iterable, Iterator, Sequence

config: Incomplete
compartment_finder: Incomplete

class Reaction(Object):
    subsystem: Incomplete
    def __init__(self, id: str | None = None, name: str = '', subsystem: str = '', lower_bound: float = 0.0, upper_bound: float | None = None, **kwargs) -> None: ...
    @property
    def reverse_id(self) -> str: ...
    @property
    def flux_expression(self) -> Variable | None: ...
    @property
    def forward_variable(self) -> Variable | None: ...
    @property
    def reverse_variable(self) -> Variable | None: ...
    @property
    def objective_coefficient(self) -> float: ...
    @objective_coefficient.setter
    def objective_coefficient(self, value: float) -> None: ...
    def __copy__(self) -> Reaction: ...
    def __deepcopy__(self, memo: dict) -> Reaction: ...
    def update_variable_bounds(self) -> None: ...
    @property
    def lower_bound(self) -> float: ...
    @lower_bound.setter
    @resettable
    def lower_bound(self, value: float) -> None: ...
    @property
    def upper_bound(self) -> float: ...
    @upper_bound.setter
    @resettable
    def upper_bound(self, value: float) -> None: ...
    @property
    def bounds(self) -> tuple[float, float]: ...
    @bounds.setter
    @resettable
    def bounds(self, value: tuple[float, float] | Sequence[float]) -> None: ...
    @property
    def flux(self) -> float: ...
    @property
    def reduced_cost(self) -> float: ...
    @property
    def metabolites(self) -> dict[Metabolite, float]: ...
    @property
    def genes(self) -> frozenset: ...
    def update_genes_from_gpr(self) -> None: ...
    @property
    def gene_reaction_rule(self) -> str: ...
    @gene_reaction_rule.setter
    @resettable
    def gene_reaction_rule(self, new_rule: str) -> None: ...
    @property
    def gene_name_reaction_rule(self): ...
    @property
    def gpr(self) -> GPR: ...
    @gpr.setter
    @resettable
    def gpr(self, value: GPR) -> None: ...
    @property
    def functional(self) -> bool: ...
    @property
    def x(self) -> float: ...
    @property
    def y(self) -> float: ...
    @property
    def reversibility(self) -> bool: ...
    @reversibility.setter
    def reversibility(self, value: bool) -> None: ...
    @property
    def boundary(self) -> bool: ...
    @property
    def model(self) -> Model | None: ...
    def remove_from_model(self, remove_orphans: bool = False) -> None: ...
    def delete(self, remove_orphans: bool = False) -> None: ...
    def copy(self) -> Reaction: ...
    def __add__(self, other: Reaction) -> Reaction: ...
    __radd__ = __add__
    def __iadd__(self, other: Reaction) -> Reaction: ...
    def __sub__(self, other: Reaction) -> Reaction: ...
    def __isub__(self, other: Reaction) -> Reaction: ...
    def __imul__(self, coefficient: float) -> Reaction: ...
    def __mul__(self, coefficient: float) -> Reaction: ...
    @property
    def reactants(self) -> list[Metabolite]: ...
    @property
    def products(self) -> list[Metabolite]: ...
    def get_coefficient(self, metabolite_id: str | Metabolite) -> float: ...
    def get_coefficients(self, metabolite_ids: Iterable[str | Metabolite]) -> Iterator[float]: ...
    def add_metabolites(self, metabolites_to_add: dict[Metabolite, float], combine: bool = True, reversibly: bool = True) -> None: ...
    def subtract_metabolites(self, metabolites: dict[Metabolite, float], combine: bool = True, reversibly: bool = True) -> None: ...
    @property
    def reaction(self) -> str: ...
    @reaction.setter
    def reaction(self, value: str) -> None: ...
    def build_reaction_string(self, use_metabolite_names: bool = False) -> str: ...
    def check_mass_balance(self) -> dict[str, float]: ...
    @property
    def compartments(self) -> set: ...
    def get_compartments(self) -> list: ...
    def knock_out(self) -> None: ...
    def build_reaction_from_string(self, reaction_str: str, verbose: bool = True, fwd_arrow: AnyStr | None = None, rev_arrow: AnyStr | None = None, reversible_arrow: AnyStr | None = None, term_split: str = '+') -> None: ...
    def summary(self, solution: Solution | None = None, fva: float | pd.DataFrame | None = None) -> ReactionSummary: ...
