from .. import Model as Model
from ..core.object import Object as Object

class Species(Object):
    def __init__(self, id: str | None = None, name: str | None = None, **kwargs) -> None: ...
    @property
    def reactions(self) -> frozenset: ...
    def copy(self) -> Species: ...
    @property
    def model(self) -> Model | None: ...
