repository: HelikarLab/MADRID

# this property is useful for conditional filtering of content that is separate from the PDF.
output: web

# this appears on the top navigation bar next to the home button
topnav_title: MADRID Documentation

# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
site_title: MADRID Documentation

# this appears in the footer
company_name: Helikar Lab

# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.
github_editme_path: HelikarLab/MADRID/blob/master/

# if you have google-analytics ID, put it in. if not, edit this value to blank.
google_analytics:

# the preview server used. Leave as is.
host: 127.0.0.1

# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts. in that case, use another port such as 4006.
port: 4000

# these are the files and directories that jekyll will exclude from the build
exclude:
  - .idea/
  - .gitignore
  - vendor

feedback_subject_line: MADRID Documentation Feedback

# used as a contact email for the Feedback link in the top navigation bar
feedback_email: jloecker3@huskers.unl.edu

# feedback_disable: true
# if you uncomment the previous line, the Feedback link gets removed

# feedback_text: "Need help?"
# if you uncomment the previous line, it changes the Feedback text

# if you uncomment the following line, it changes where the feedback link points to
feedback_link: "https://github.com/HelikarLab/MADRID/issues"

# library used for syntax highlighting
highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true
collections:
  tooltips:
    output: false


# these are defaults used for the frontmatter for these file types
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      # if you don't want to use Commento.io and just hide comments, change true to false wherever you see the comments property
      comments: false
      search: true
      sidebar: home_sidebar
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      # if you don't want to use Commento.io and just hide comments, change true to false wherever you see the comments property
      comments: false
      search: true
      sidebar: home_sidebar
      topnav: topnav


sidebars:
- home_sidebar
- mydoc_sidebar
- product1_sidebar
- product2_sidebar
- other

# the description is used in the feed.xml file
description: "Intended as a documentation theme based on Jekyll for technical writers documenting software and other technical products, this theme has all the elements you would need to handle multiple products with both multi-level sidebar navigation, tags, and other documentation features."

# needed for sitemap.xml file only
# url: http://idratherbewriting.com
# baseurl: /documentation-theme-jekyll


github: [metadata]
livereload: true
