---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(tidyverse)
```


```{r}
z_result <- function(z_vector, density, mu, stdev, max_y) {
  z_res <- list(
    z = z_vector,
    d = density,
    m = mu,
    s = stdev,
    max_y = max_y
  )

  class(z_vector) <- append(class(z_res), "zFPKM")
  return(z_res)
}
```

```{r}
z_score_calc <- function(abundance) {
  if (!is.numeric(abundance)) {
    stop("argument 'fpkm' must be numeric")
  }

  log_abundance_filt <- log(abundance[abundance>0], base=2)
  log_abundance <- log(abundance, base=2)

  d <- density(log_abundance_filt)
  mu <- d[["x"]][which.max(d[["y"]])]
  max_y <- max(d[["y"]])

  # standard deviation from right side
  #U <- mean(log_abundance[log_abundance > mu])
  #stdev <- (U - mu) * sqrt(pi / 2)
  # standard deviation from left side
  U <- mean(log_abundance[log_abundance < mu & log_abundance > 0])
  stdev <- (mu - U) * sqrt(pi / 2)


  # Compute ztransform
  z <- (log_abundance - mu) / stdev


  result <- z_result(z, d, mu, stdev, max_y)

  return(result)
}

```

```{r}
plot_gaussian_fit <- function(results, FacetTitles=TRUE, PlotXfloor) {

  df <- data.frame()

  for (name in names(results)) {
    result <- results[[name]]
    d <- result[["d"]]
    mu <- result[["m"]]
    stdev <- result[["s"]]
    max_y <- result[["max_y"]]

    fitted <- dnorm(d[["x"]], mean=mu, sd=stdev)
    max_abundance <- max_y
    max_fit <- max(fitted)

    scale_fit <- fitted * (max_abundance / max_fit)

    new_df <- data.frame(sample_name=name, log_abundance=d[["x"]], abundance_density=d[["y"]],
                     fitted_density_scaled=scale_fit)


    df <- df %>% dplyr::bind_rows(new_df)
  }

  df_stack <- df %>% tidyr::gather(source, density, -c(log_abundance, sample_name))
  labels <- unique(df_stack$sample_name)

  maximum_x = max(df_stack[["log_abundance"]])
  #maximum_y = max(d[["y"]])

  p <- ggplot2::ggplot(df_stack, ggplot2::aes(x=log_abundance, y=density, color=source)) +
    #ggplot2::facet_wrap(~ sample_name) +
    ggplot2::facet_wrap(vars(sample_name)) +
    ggplot2::geom_line(alpha=0.7) +
    ggplot2::theme_bw() +
    ggplot2::labs(x="log2(abundance)", y="[scaled] density")  +
    ggplot2::theme(legend.position="top") +
    ggplot2::xlim(PlotXfloor, maximum_x)


  print(p)
}
```

```{r}
z_transform <- function(abundance_df) {

  abundance_df <- rm_infinite(abundance_df)

  z_df <- data.frame(row.names=row.names(abundance_df))
  outputs <- list()
  for (c in colnames(abundance_df)) {
    output <- z_score_calc(abundance_df[, c])
    z_df[, c] <- output[["z"]]
    outputs[[c]] <- output
  }

  return(list(outputs, z_df))
}
```

```{r}
z_score_plot <- function(abundance_df, FacetTitles=FALSE, PlotXfloor=-20) {
  plot_gaussian_fit(z_transform(abundance_df)[[1]], FacetTitles, PlotXfloor)
}

```

```{r}
rm_infinite <- function(fpkm) {
  # Remove FPKM rows containing all NaN values. These are most likely a result
  # of effective lengths = 0 when calculating FPKM.
  return(fpkm[which(!apply(fpkm, 1, function(r) all(is.nan(r) | is.infinite(r)))), ])
}
```

```{r}
setwd("/Users/joshl/Downloads/NormTransformTest")
dir.create("figures", showWarnings = FALSE)
prot <- read.csv("/Users/joshl/PycharmProjects/MADRID/pipelines/data/data_matrices/Naive/ProteomicsDataMatrix_Naive.csv")

plot_batches <- ceiling(ncol(prot)-2)/6

for ( i in 1:plot_batches) {
  png(file.path("figures", paste0("fit_prot_", i, ".png")))
  z_score_plot(prot[,c((i-1)*6+3, (i-1)*6+4, (i-1)*6+5, (i-1)*6+6, (i-1)*6+7, (i-1)*6+8)])
  dev.off()
  #if ( i ==1 ) {stop()}
}
z_transformed_abundances <- z_transform(prot[,c(-1, -2)])[[2]]

```
