import pandas as pd
from ..core import Configuration as Configuration, Gene as Gene, Model as Model, Reaction as Reaction
from ..util import ProcessPool as ProcessPool
from .moma import add_moma as add_moma
from .room import add_room as add_room
from _typeshed import Incomplete
from cobra import Solution as Solution

configuration: Incomplete

def single_reaction_deletion(model: Model, reaction_list: list[Reaction | str] | None = None, method: str = 'fba', solution: Solution | None = None, processes: int | None = None, **kwargs) -> pd.DataFrame: ...
def single_gene_deletion(model: Model, gene_list: list[Gene | str] | None = None, method: str = 'fba', solution: Solution | None = None, processes: int | None = None, **kwargs) -> pd.DataFrame: ...
def double_reaction_deletion(model: Model, reaction_list1: list[Reaction | str] | None = None, reaction_list2: list[Reaction | str] | None = None, method: str = 'fba', solution: Solution | None = None, processes: int | None = None, **kwargs) -> pd.DataFrame: ...
def double_gene_deletion(model: Model, gene_list1: list[Gene | str] | None = None, gene_list2: list[Gene | str] | None = None, method: str = 'fba', solution: Solution | None = None, processes: int | None = None, **kwargs) -> pd.DataFrame: ...

class KnockoutAccessor:
    def __init__(self, pandas_obj: pd.DataFrame | pd.Series) -> None: ...
    def __getitem__(self, args: Gene | list[Gene] | set[Gene] | list[set[Gene]] | Reaction | list[Reaction] | set[Reaction] | list[set[Reaction]] | str | list[str] | set[str] | list[set[str]]) -> pd.DataFrame: ...
