from ..core import get_solution as get_solution
from ..util import create_stoichiometric_matrix as create_stoichiometric_matrix, nullspace as nullspace
from .helpers import normalize_cutoff as normalize_cutoff
from cobra import Model as Model, Reaction as Reaction, Solution as Solution

def add_loopless(model: Model, zero_cutoff: float | None = None) -> None: ...
def loopless_solution(model: Model, fluxes: dict[str, float] | None = None) -> Solution: ...
def loopless_fva_iter(model: Model, reaction: Reaction, solution: bool = False, zero_cutoff: float | None = None) -> float | dict[str, float]: ...
