from .parsimonious import pfba as pfba
from cobra.core import Model as Model, Solution as Solution

def moma(model: Model, solution: Solution | None = None, linear: bool = True) -> Solution: ...
def add_moma(model: Model, solution: Solution | None = None, linear: bool = True) -> None: ...
