from ..core.solution import get_solution as get_solution
from cobra import Model as Model, Reaction as Reaction, Solution as Solution
from optlang.interface import Objective as Objective
from typing import Callable

def optimize_minimal_flux(*args, **kwargs) -> Callable[[Model, float, dict | Objective, list['Reaction']], 'Solution']: ...
def pfba(model: Model, fraction_of_optimum: float = 1.0, objective: dict | Objective | None = None, reactions: list['Reaction'] | None = None) -> Solution: ...
def add_pfba(model: Model, objective: dict | Objective | None = None, fraction_of_optimum: float = 1.0) -> None: ...
