from ..core import Reaction as Reaction
from cobra import Model as Model

def assess(model: Model, reaction: Reaction | str, flux_coefficient_cutoff: float = 0.001, solver: str = None) -> bool | dict: ...
def assess_component(model: Model, reaction: Reaction | str, side: str, flux_coefficient_cutoff: float = 0.001, solver: str = None) -> bool | dict: ...
def assess_precursors(model: Model, reaction: Reaction, flux_coefficient_cutoff: float = 0.001, solver: str = None) -> bool | dict: ...
def assess_products(model: Model, reaction: Reaction, flux_coefficient_cutoff: float = 0.001, solver: str = None) -> bool | dict: ...
