from .parsimonious import pfba as pfba
from cobra import Model as Model, Solution as Solution

def room(model: Model, solution: Solution | None = None, linear: bool = False, delta: float = 0.03, epsilon: float = 0.001) -> Solution: ...
def add_room(model: Model, solution: Solution | None = None, linear: bool = False, delta: float = 0.03, epsilon: float = 0.001) -> None: ...
