# Add theme, from: https://github.com/pages-themes/cayman
remote_theme: "pages-themes/cayman@v0.2.0"
plugins:
  - "jekyll-remote-theme"
  - "jekyll-menus"

title: "MADRID"
description: "MADRID: Metabolic Drug Repurposing Identification"
show_downloads: true

github:
  name: "MADRID"
  url: "https://github.com/HelikarLab/MADRID"
  tagline: ""
  brandt_url: "https://github.com/babessell1"
  josh_url: "https://github.com/JoshLoecker"

docker:
  name: "babessell/madrid"
  tag: "development"
  url: "https://hub.docker.com/r/babessell/madrid"
