# Add theme, from: https://github.com/pages-themes/cayman
remote_theme: "pages-themes/cayman@v0.2.0"
plugins:
  - "jekyll-remote-theme"

title: "MADRID"
description: "MADRID: Metabolic Drug Repurposing Identification"
show_downloads: true

github:
  name: "MADRID"
  url: "https://github.com/HelikarLab/MADRID"
  tagline: ""
  brandt_url: "https://github.com/babessell1"
  josh_url: "https://github.com/JoshLoecker"

docker:
  name: "ghcr.io/helikarlab/madrid"
  tag: "[CHOSEN-TAG]"
  all_tags: "https://github.com/HelikarLab/MADRID/pkgs/container/madrid/versions"

# Static images in assets/img
defaults:
  - scope:
      path: "/assets/img"
    values:
      image: true
