from cobra import Object as Object
from typing import Any, Callable

class HistoryManager:
    def __init__(self, **kwargs) -> None: ...
    def __call__(self, operation: Callable[[Any], Any]) -> None: ...
    def reset(self) -> None: ...
    def size(self) -> int: ...

def get_context(obj: Object) -> HistoryManager | None: ...
def resettable(func: Callable[[Any], Any]) -> Callable[[Any], Any]: ...
