from types import TracebackType
from typing import Any, Callable

__all__ = ['ProcessPool']

class ProcessPool:
    def __init__(self, processes: int | None = None, initializer: Callable | None = None, initargs: tuple = (), maxtasksperchild: int | None = None, **kwargs) -> None: ...
    def __getattr__(self, name: str, **kwargs) -> Any: ...
    def __enter__(self) -> ProcessPool: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> bool | None: ...
    def close(self) -> None: ...
