import optlang
import pandas as pd
from _typeshed import Incomplete
from cobra import Model as Model, Reaction as Reaction
from cobra.exceptions import OPTLANG_TO_EXCEPTIONS_DICT as OPTLANG_TO_EXCEPTIONS_DICT, OptimizationError as OptimizationError, SolverNotFound as SolverNotFound
from cobra.util.context import get_context as get_context
from types import ModuleType
from typing import NamedTuple

CONS_VARS: Incomplete
logger: Incomplete
solvers: Incomplete
qp_solvers: Incomplete
has_primals: Incomplete

class Components(NamedTuple):
    variable: optlang.interface.Variable
    upper_constraint: optlang.interface.Constraint
    lower_constraint: optlang.interface.Constraint

def linear_reaction_coefficients(model: Model, reactions: list['Reaction'] | None = None) -> dict['Reaction', float]: ...
def set_objective(model: Model, value: optlang.interface.Objective | optlang.symbolics.Basic | dict['Reaction', float], additive: bool = False) -> None: ...
def interface_to_str(interface: str | ModuleType) -> str: ...
def get_solver_name(mip: bool = False, qp: bool = False) -> str: ...
def choose_solver(model: Model, solver: str | None = None, qp: bool = False) -> ModuleType: ...
def check_solver(obj): ...
def add_cons_vars_to_problem(model: Model, what: list[CONS_VARS] | tuple[CONS_VARS] | Components, **kwargs) -> None: ...
def remove_cons_vars_from_problem(model: Model, what: list[CONS_VARS] | tuple[CONS_VARS] | Components) -> None: ...
def add_absolute_expression(model: Model, expression: str, name: str = 'abs_var', ub: float | None = None, difference: float = 0.0, add: bool = True) -> Components: ...
def fix_objective_as_constraint(model: Model, fraction: float = 1.0, bound: float | None = None, name: str = 'fixed_objective_{}') -> float: ...
def check_solver_status(status: str = None, raise_error: bool = False) -> None: ...
def assert_optimal(model: Model, message: str = 'Optimization failed') -> None: ...
def add_lp_feasibility(model: Model) -> None: ...
def add_lexicographic_constraints(model: Model, objectives: list['Reaction'], objective_direction: str | list[str] = 'max') -> pd.Series: ...
