from typing import Any

def format_long_string(string: str, max_length: int = 50) -> str: ...

class AutoVivification(dict):
    def __getitem__(self, item: Any) -> Any: ...

def show_versions() -> None: ...
