name: Continuous Delivery
on:
  workflow_dispatch:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DEBIAN_FRONTEND: noninteractive

jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    name: Build Docker Image

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.GITHUB_REF }}

      # Get tag/release information for docker tags
      - name: Docker Metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=false
            prefix=
            suffix=
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') && endsWith(github.ref, 'master') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up jupyter notebook output cleaning
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Clean Notebook Output
        run: |
          python -m pip install --upgrade nbstripout --no-cache-dir
          find $GITHUB_WORKSPACE -name "*.ipynb" -exec nbstripout "{}" \;

      - name: Assert no outputs present in jupyter notebook
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      # Log into the GitHub Container Registry so we can push the image
      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64
          file: ./Dockerfile
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
