name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: "true"
          cache-suffix: "${{ matrix.python-version }}"
          cache-dependency-glob: 'uv.lock'

      - name: Install Dependencies
        run: uv sync --python "${{ matrix.python-version }}" --all-extras --dev

      - name: Run tests
        run: uv run --python "${{ matrix.python-version }}" pytest --cov --junitxml=junit.xml -o junit_family=legacy

      - name: Cache Clear
        run: uv cache prune --ci
