name: Continuous Integration
on:
# Remove "push" and instead build every day at midnight - this allows for multiple pushes to happen before building the image
# Manually building the image is possible inside GitHub if needed
#  push:
#    branches:
#      - 'bulk_dev'
#      - "master"
  workflow_dispatch:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DEBIAN_FRONTEND: noninteractive

jobs:
  # This job will check if there has been a push to the master branch within the past day
  # If there has been a push to the master branch, then it will run the build job
  # From: https://github.com/doxygen/doxygen/blob/68b134f1457aa88553665c3bb77b85154436bf4c/.github/workflows/coverity.yml#L16
  build-and-push-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    name: Build Docker Image

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.GITHUB_REF }}

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Get tag/release information for docker tags
      - name: Docker Metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=false
            prefix=
            suffix=
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/master') }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Fail if prehook not used
      - name: Clean Notebook Output
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
        run: |
          python -m pip install --upgrade nbstripout --no-cache-dir
          nbstripout /home/runner/work/MADRID/MADRID/*.ipynb

      # Fail if prehook not used
      - name: Clean Notebook Output
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
