name: Continuous Integration
on:
# Remove "push" and instead build every day at midnight - this allows for multiple pushes to happen before building the image
# Manually building the image is possible inside GitHub if needed
#  push:
#    branches:
#      - 'bulk_dev'
#      - "master"
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight

jobs:
  dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v3.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: babessell/madrid:development
