name: Continuous Integration
on:
# Remove "push" and instead build every day at midnight - this allows for multiple pushes to happen before building the image
# Manually building the image is possible inside GitHub if needed
#  push:
#    branches:
#      - 'bulk_dev'
#      - "master"
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight

jobs:
  # This job will check if there has been a push to the master branch within the past day
  # From: https://github.com/doxygen/doxygen/blob/68b134f1457aa88553665c3bb77b85154436bf4c/.github/workflows/coverity.yml#L16
  check_build:
    runs-on: ubuntu-20.04
    name: Check Latest Commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Latest Commit Hash
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: Check if commit <24 hours
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(github rev-list --after="24 hours" %{{ github.sha }}) && echo "::set-output name=should_run::false"


  dockerhub:

    # Only run the docker build if we have a commit within the past 24 hours
    needs: check_build
    if: ${{ needs.check_build.outputs.should_run != 'false' }}
    runs-on: ubuntu-latest
    name: Build Docker Image

    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set the tag based on the current branch
      - name: Get Branch Name
        run: |
          if ${{ github.ref_name == 'master }} echo 'DOCKER_TAG=development' >> $DOCKER_TAG
          else echo 'DOCKER_TAG={{ github.ref_name }}' >> $DOCKER_TAG

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: babessell/madrid:${{env.DOCKER_TAG}}
