name: Format
on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Create Virtual Environment
        run: uv venv

      - name: Install Jupyter
        run: uv pip install jupyter nbconvert

      - name: Strip Notebook Output
        run: uv run jupyter nbconvert --clear-output --inplace "main/COMO.ipynb"

      - name: Format Python Imports
        uses: astral-sh/ruff-action@v1
        with:
          args: "check --fix --select I"

      - name: Format code
        uses: astral-sh/ruff-action@v1
        with:
          args: "format"

      - name: Format Notebook
        uses: astral-sh/ruff-action@v1
        with:
          args: "format main/COMO.ipynb"

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: format code, Jupyter Notebook(s), and Python imports with `ruff`"
          file_pattern: "main/como/*.py"
