# This action will publish the COMO notebook to github pages

name: Publish COMO

on:
  push:
    branches:
      - feature/jupyter-pages

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: "3.10"


      - name: Install dependencies
        run: |
          conda init bash
          source ~/.bashrc
          conda activate base
          conda install -c conda-forge mamba
          mamba env update --name base --file environment.yaml

      - name: List conda packages
        run: mamba list
          

