# This action will publish the COMO notebook to github pages

name: Publish COMO

on:
  push:
    branches:
      - feature/jupyter-pages

jobs:
  deploy-como:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Install dependencies in conda environment
      - name: Install Micromamba
        # Execute '"${SHELL}" <(curl -L micro.mamba.pm/install.sh)'
        run: |
          curl -L "https://micro.mamba.pm/install.sh" > micromamba.sh
          chmod +x micromamba.sh
          ./micromamba.sh shell init -s bash -p ~/micromamba
          source ~/.bashrc
          micromamba create --name como
          micromamba activate como-env
          micromamba env update --file environment.yaml
        env:
          PATH: ${{ runner.workspace }}/micromamba:$PATH

      - name: List conda packages
        run: mamba list
          

