# This action will publish the COMO notebook to github pages

name: Publish COMO

on:
  push:
    branches:
      - feature/jupyter-pages

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Install dependencies in conda environment
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          auto-update-conda: true
          activate-environment: base

          environment-file: environment.yaml
          auto-activate-base: true

      - name: List conda packages
        run: mamba list
          

