# This action will publish the COMO notebook to github pages

name: Publish COMO

on:
  push:
    branches:
      - feature/jupyter-pages

jobs:
  deploy-como:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Install dependencies in conda environment
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10"
          mamba-version: "*"
          channels: bioconda,conda-forge,r,gurobi,defaults
          channel-priority: true
          auto-update-conda: true
          activate-environment: base
          auto-activate-base: true
          environment-file: environment.yaml


      - name: List conda packages
        run: mamba list
          

