# This action will publish the COMO notebook to github pages

name: Publish COMO

on:
  push:
    branches:
      - feature/jupyter-pages

jobs:
  deploy-como:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Install dependencies in conda environment
      - name: Install Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '*'
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true
          post-cleanup: 'none'
          environment-name: como
          init-shell: bash

      - name: List conda packages
        run: mamba list
          

