# This action will publish the COMO notebook to github pages

name: Publish COMO

on:
  push:
    branches:
      - feature/jupyter-pages

jobs:
  deploy-como:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install dependencies in conda environment
      - name: Install Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: "latest"
          environment-file: ${{ github.workspace }}/environment.yml
          cache-environment: true
          cache-downloads: true
          post-cleanup: "none"
          environment-name: como
          init-shell: bash

      - name: List installed packages
        run: mamba list
          

