name: Unit Tests
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize


jobs:
  unit-tests:
    runs-on: ubuntu-latest

    # Using a matrix lets us define additional versions of Python to test against
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install Dependencies
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest

