name: Unit Tests
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize


jobs:
  unit-tests:
    runs-on: ubuntu-latest

    # Using a matrix lets us define additional versions of Python to test against
    strategy:
      matrix:
        python-version: [ "3.10" ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: main/tests/environment.yaml
          environment-name: como_tests
          micromamba-version: "latest"
          init-shell: bash
          cache-environment: true
          cache-environment-key: ${{ runner.os }}-conda-${{ hashFiles('main/tests/environment.yaml') }}
          post-cleanup: "none"

      - name: Run tests
        run: python -m pytest
