name: Unit Tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:


jobs:
    unit-tests:
      runs-on: ubuntu-latest

      # Using a matrix lets us define additional versions of Python to test against
      strategy:
        matrix:
          python-version: ["3.10"]

      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Install Conda environment
          uses: mamba-org/provision-with-micromamba@main
          with:
            environment-file: main/py/tests/environment.yaml
            environment-name: como_tests
            extra-specs: |
              python=${{ matrix.python-version }}

        - name: Run tests
          run: |
            # Initialize micromamba and activate como_tests environment
            eval "$(micromamba shell hook --shell=bash)" && micromamba activate como_tests
            python -m pytest
